insert into PValues(id, name, description) values (1, "Zdravie", "his project is served and bundled with Vite. The recommended IDE setup is VSCode + Volar. If you need to test your components and web pages, check out Cypress and Cypress Component Testing.");
insert into PValues(id, name, description) values (2, "Kariera", "Get official tools and libraries for your project: Pinia, Vue Router, Vue Test Utils, and Vue Dev Tools.");
insert into PValues(id, name, description) values (3, "Investicie", "As an independent project, Vue relies on community backing for its sustainability.");
insert into PValues(id, name, description) values (4, "Majetok", "Get official tools and libraries for your project:");
insert into PValues(id, name, description) values (5, "Zabava a Volny Cas", "provides you with all information you need to get started.");
insert into PValues(id, name, description) values (6, "Vztahy", "provides you with all information you need to get started.");
insert into PValues(id, name, description) values (7, "Sebarozvoj", "need to get started.");


insert into Objectives(id, value_id, state, name, description, date_created, date_finished) values (1, 1, "achieved", "nefajcit", "some description","10/03/2023", "15/03/2023");
insert into Objectives(id, value_id, state, name, description, date_created, date_finished) values (2, 1, "active", "zdravy chrbat", "some other description", "10/03/2023","");
insert into Objectives(id, value_id, state, name, description, date_created, date_finished) values (3, 1, "failed", "dychanie", "third description","10/03/2023", "10/04/2023");
insert into Objectives(id, value_id, state, name, description, date_created, date_finished) values (4, 2, "achieved", "bc. na ESF", "ukoncit uspesne Podnikove Hospodarstvo a Management na ESF MU", "20/09/2012", "15/01/2019");
insert into Objectives(id, value_id, state, name, description, date_created, date_finished) values (5, 2, "failed", "Mgr. na FI", "ukoncit uspesne SSME na FI MU", "20/09/2019", "10/09/2021");
insert into Objectives(id, value_id, state, name, description, date_created, date_finished) values (6, 4, "active", "bmw", "namakane", "10/03/2023", "");
insert into Objectives(id, value_id, state, name, description, date_created, date_finished) values (7, 1, "active", "xxx", "xxx xxx xxx", "10/03/2023", "");
insert into Objectives(id, value_id, state, name, description, date_created, date_finished) values (8, 1, "active", "xxx", "xxx xxx xxx", "10/03/2023", "");
insert into Objectives(id, value_id, state, name, description, date_created, date_finished) values (9, 1, "active", "xxx", "xxx xxx xxx", "10/03/2023", "");
insert into Objectives(id, value_id, state, name, description, date_created, date_finished) values (10, 1, "active", "xxx", "xxx xxx xxx", "10/03/2023", "");
insert into Objectives(id, value_id, state, name, description, date_created, date_finished) values (11, 3, "active", "xxx", "xxx xxx xxx", "10/03/2023", "");


insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (1, 4, "completed", "semester podzim17", "", "", "", "", "", "", "", "");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (2, 4, "completed", "semester jaro18", "", "", "", "", "", "", "", "");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (3, 4, "completed", "bakalarka", "", "", "", "", "", "", "", "");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (4, 4, "failed", "statnice", "", "", "", "", "", "", "", "");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (5, 4, "completed", "opravne statnice", "", "", "", "", "", "", "", "");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (6, 5, "completed", "zacat Mgr studium", "", "", "", "", "", "", "", "");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (7, 5, "completed", "semester podzim19", "", "", "", "", "", "", "", "");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (8, 5, "completed", "semester jaro20", "", "", "", "", "", "", "", "");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (9, 5, "completed", "semester podzim20", "", "", "", "", "", "", "", "");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (10, 5, "failed", "semester jaro21", "", "", "", "", "", "", "", "");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (11, 5, "completed", "zacat druhe Mgr studium", "", "", "", "", "", "", "", "");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (12, 5, "failed", "semester jaro22", "", "", "", "", "", "", "", "");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (13, 2, "completed", "aaa with description", "description is here", "s", "m", "a", "r", "t", "10/03/2023", "10/03/2023");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (14, 2, "failed", "bbb", "", "", "", "", "", "", "10/03/2023", "10/03/2023");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (15, 2, "active", "ccc", "", "", "", "", "", "", "10/03/2023", "10/03/2023");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (16, 11, "active", "a", "", "", "", "", "", "", "10/03/2020", "10/03/2023");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (17, 11, "completed", "b", "", "", "", "", "", "", "10/03/2020", "20/03/2023");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (18, 11, "active", "c", "", "", "", "", "", "", "10/03/2020", "08/03/2023");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (19, 11, "failed", "d", "", "", "", "", "", "", "10/03/2020", "10/12/2022");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (20, 11, "active", "e", "", "", "", "", "", "", "10/03/2020", "10/01/2023");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (21, 11, "completed", "f", "", "", "", "", "", "", "10/03/2020", "10/03/2023");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (22, 11, "active", "g", "", "", "", "", "", "", "10/03/2020", "10/03/2022");


insert into Tasks(id, kr_id, state, value) values (1, 1, "finished", "Management - zk");
insert into Tasks(id, kr_id, state, value) values (2, 1, "finished", "Ekonometria - zk");
insert into Tasks(id, kr_id, state, value) values (3, 1, "finished", "Bakalarky Seminar - z");
insert into Tasks(id, kr_id, state, value) values (4, 1, "finished", "AJ3 - z");
insert into Tasks(id, kr_id, state, value) values (5, 2, "finished", "TV2 - z");
insert into Tasks(id, kr_id, state, value) values (6, 2, "finished", "Bakalarky Seminar 2 - z");
insert into Tasks(id, kr_id, state, value) values (7, 2, "finished", "AJ3 - zl");
insert into Tasks(id, kr_id, state, value) values (8, 3, "finished", "teoreticka cast");
insert into Tasks(id, kr_id, state, value) values (9, 3, "finished", "prakticka cast");
insert into Tasks(id, kr_id, state, value) values (10, 3, "finished", "vytlacena & odovzdana");
insert into Tasks(id, kr_id, state, value) values (11, 4, "finished", "obhajoba");
insert into Tasks(id, kr_id, state, value) values (12, 4, "finished", "ekonomia");
insert into Tasks(id, kr_id, state, value) values (13, 4, "failed", "management");
insert into Tasks(id, kr_id, state, value) values (14, 5, "finished", "management");
insert into Tasks(id, kr_id, state, value) values (15, 6, "finished", "prihlaska");
insert into Tasks(id, kr_id, state, value) values (16, 6, "finished", "obj=4 is achieved");
insert into Tasks(id, kr_id, state, value) values (17, 6, "finished", "prijimacky");
insert into Tasks(id, kr_id, state, value) values (18, 6, "finished", "zapis");
insert into Tasks(id, kr_id, state, value) values (19, 7, "finished", "FI:PA017 Software Engineering II");
insert into Tasks(id, kr_id, state, value) values (20, 7, "finished", "FI:PA116 Domain Understanding and Modeling");
insert into Tasks(id, kr_id, state, value) values (21, 7, "finished", "FI:PA194 Introduction to Service Science");
insert into Tasks(id, kr_id, state, value) values (22, 7, "finished", "FI:PV206 Communication and Soft Skills");
insert into Tasks(id, kr_id, state, value) values (23, 7, "finished", "FI:PA103 OOAD Methods");
insert into Tasks(id, kr_id, state, value) values (24, 7, "failed", "ESF:MKE_MIE2 Mikroekonomie 2");
insert into Tasks(id, kr_id, state, value) values (25, 8, "finished", "FSS:PSYb1280 Psychologie v běžném životě");
insert into Tasks(id, kr_id, state, value) values (26, 8, "finished", "FI:PA165 Enterprise Applications in Java");
insert into Tasks(id, kr_id, state, value) values (27, 8, "finished", "FI:PA179 Project Management");
insert into Tasks(id, kr_id, state, value) values (28, 8, "finished", "FI:PV239 Vývoj aplikací pro mobilní platformy");
insert into Tasks(id, kr_id, state, value) values (29, 8, "finished", "ESF:MKE_MAE2 Makroekonomie 2");
insert into Tasks(id, kr_id, state, value) values (30, 8, "failed", "ESF:MPV_RKMD Rozvoj komunikačních a manažerských dovedností");
insert into Tasks(id, kr_id, state, value) values (31, 9, "finished", "FI:IV054 Coding, Cryptography and Cryptographic Protocols");
insert into Tasks(id, kr_id, state, value) values (32, 9, "finished", "FI:PA159 Počítačové sítě a jejich aplikace I");
insert into Tasks(id, kr_id, state, value) values (33, 9, "finished", "FI:PV241 Enterprise and Financial Management");
insert into Tasks(id, kr_id, state, value) values (34, 9, "finished", "FI:PV248 Python");
insert into Tasks(id, kr_id, state, value) values (35, 9, "finished", "ESF:MKE_MIE2 Mikroekonomie 2");
insert into Tasks(id, kr_id, state, value) values (36, 9, "finished", "ESF:MKF_ACP1 Analýza cenných papírů 1");
insert into Tasks(id, kr_id, state, value) values (37, 10, "finished", "FI:PA181 Services - Systems, Modeling and Execution");
insert into Tasks(id, kr_id, state, value) values (38, 10, "finished", "FI:PV207 Business Process Management");
insert into Tasks(id, kr_id, state, value) values (39, 10, "finished", "ESF:MPV_RKMD Rozvoj komunikačních a manažerských dovedností");
insert into Tasks(id, kr_id, state, value) values (40, 10, "failed", "FI:PV215 Management by Competencies");
insert into Tasks(id, kr_id, state, value) values (41, 10, "failed", "FI:MV013 Statistics for Computer Science");
insert into Tasks(id, kr_id, state, value) values (42, 10, "failed", "FI:PA152 Efficient Use of Database Systems");