insert into PValues(id, name, description) values (1, "Zdravie", "his project is served and bundled with Vite ... out Cypress and Cypress Component Testing.");
insert into PValues(id, name, description) values (2, "Second", "ha");
insert into PValues(id, name, description) values (3, "Third", "with objectives");
insert into PValues(id, name, description) values (4, "Modifable", "x");
insert into PValues(id, name, description) values (5, "New Static", "xxx");

insert into Objectives(id, value_id, state, name, description, date_created, date_finished) values (1, 3, "achieved", "obj1", "some description", "10/03/2023", "12/03/2023");
insert into Objectives(id, value_id, state, name, description, date_created, date_finished) values (2, 3, "active", "obj2", "some other description", "10/03/2023", "");
insert into Objectives(id, value_id, state, name, description, date_created, date_finished) values (3, 3, "failed", "obj3", "third description", "10/04/2023", "12/04/2023");
insert into Objectives(id, value_id, state, name, description, date_created, date_finished) values (4, 4, "active", "Add More", "test kr inserts", "10/03/2023", "");
insert into Objectives(id, value_id, state, name, description, date_created, date_finished) values (5, 4, "active", "To Clear", "test kr deletions", "10/03/2023", "");
insert into Objectives(id, value_id, state, name, description, date_created, date_finished) values (6, 4, "active", "Needs Tasks", "test task add/del", "10/03/2023", "");
insert into Objectives(id, value_id, state, name, description, date_created, date_finished) values (7, 4, "active", "Updatable", "for updates", "10/03/2023", "");
insert into Objectives(id, value_id, state, name, description, date_created, date_finished) values (8, 4, "active", "Finishable", "for state changes", "10/03/2023", "");
insert into Objectives(id, value_id, state, name, description, date_created, date_finished) values (9, 4, "active", "SMART", "for smart ppl", "19/05/2023", "");
insert into Objectives(id, value_id, state, name, description, date_created, date_finished) values (10, 4, "active", "ideas", "for ideas", "21/05/2023", "");
insert into Objectives(id, value_id, state, name, description, date_created, date_finished) values (11, 4, "active", "ideas", "for create", "21/05/2023", "");
insert into Objectives(id, value_id, state, name, description, date_created, date_finished) values (12, 4, "active", "ideas", "for delete", "21/05/2023", "");
insert into Objectives(id, value_id, state, name, description, date_created, date_finished) values (13, 5, "active", "tasks count", "for check", "10/05/2023", "");

insert into ObjectiveIdeas(id, objective_id, value) values (1, 10, "first");
insert into ObjectiveIdeas(id, objective_id, value) values (2, 10, "second");
insert into ObjectiveIdeas(id, objective_id, value) values (3, 10, "third");
insert into ObjectiveIdeas(id, objective_id, value) values (4, 12, "to del");

insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (1, 1, "completed", "x", "xx", "s", "m", "a", "r", "t", "10/03/2023", "11/03/2023");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (2, 2, "completed", "aaa with description", "description is here", "s", "m", "a", "r", "t", "10/03/2023", "10/03/2023");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (3, 2, "failed", "bbb", "", "", "", "", "", "", "10/03/2023", "12/03/2023");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (4, 2, "active", "ccc", "desc", "a", "b", "c", "d", "e", "10/03/2023", "13/03/2023");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (5, 3, "failed", "y", "yy", "s", "m", "a", "r", "t", "10/03/2023", "14/03/2023");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (6, 4, "active", "add one more", "", "", "", "", "", "", "10/03/2023", "12/03/2023");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (7, 5, "active", "should stay", "", "", "", "", "", "", "10/03/2023", "12/03/2023");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (8, 5, "active", "to del", "", "", "", "", "", "", "10/03/2023", "12/03/2023");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (9, 6, "active", "no change", "ddd", "q", "w", "e", "r", "t", "10/03/2023", "12/03/2023");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (10, 6, "active", "add task", "", "", "", "", "", "", "10/03/2023", "12/03/2023");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (11, 6, "active", "del task", "", "", "", "", "", "", "10/03/2023", "12/03/2023");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (12, 7, "active", "name", "description", "", "", "x", "", "", "10/03/2023", "12/03/2023");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (13, 7, "active", "review", "d", "", "y", "x", "z", "w", "10/03/2023", "12/03/2023");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (14, 7, "active", "state", "x", "2", "3", "4", "5", "6", "10/03/2023", "12/03/2023");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (15, 8, "completed", "state", "d", "a", "a", "a", "a", "6", "10/03/2023", "12/03/2023");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (16, 9, "completed", "a", "D", "s", "m", "a", "r", "t", "19/05/2023", "19/05/2023");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (17, 9, "failed", "b", "D", "s", "m", "a", "r", "t", "19/05/2023", "19/05/2023");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (18, 9, "active", "smart", "D", "s", "m", "a", "r", "t", "19/05/2023", "19/05/2023");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (19, 9, "active", "new", "D", "", "", "", "", "", "19/05/2023", "19/05/2023");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (20, 9, "active", "missing", "D", "s", "m", "", "r", "t", "19/05/2023", "19/05/2023");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (21, 9, "active", "not", "D", "s", "[!!!] m", "a", "r", "t", "19/05/2023", "19/05/2023");
insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values (22, 13, "active", "with tasks", "D", "s", "m", "a", "r", "t", "19/05/2023", "22/05/2023");

insert into Tasks(id, kr_id, state, value) values (1, 3, "failed", "task1");
insert into Tasks(id, kr_id, state, value) values (2, 4, "active", "task2.0");
insert into Tasks(id, kr_id, state, value) values (3, 2, "finished", "task3");
insert into Tasks(id, kr_id, state, value) values (4, 4, "finished", "task2.1");
insert into Tasks(id, kr_id, state, value) values (5, 4, "failed", "task2.2");
insert into Tasks(id, kr_id, state, value) values (6, 1, "finished", "achieved obj task");
insert into Tasks(id, kr_id, state, value) values (7, 5, "failed", "failed obj task");
insert into Tasks(id, kr_id, state, value) values (8, 9, "active", "no change");
insert into Tasks(id, kr_id, state, value) values (9, 10, "active", "add one more");
insert into Tasks(id, kr_id, state, value) values (10, 11, "active", "should stay");
insert into Tasks(id, kr_id, state, value) values (11, 11, "active", "to del");
insert into Tasks(id, kr_id, state, value) values (12, 22, "active", "activeX");
insert into Tasks(id, kr_id, state, value) values (13, 22, "failed", "failedX");
insert into Tasks(id, kr_id, state, value) values (14, 22, "active", "activeX");
insert into Tasks(id, kr_id, state, value) values (15, 22, "finished", "finishedX");
insert into Tasks(id, kr_id, state, value) values (16, 22, "finished", "finishedX");
insert into Tasks(id, kr_id, state, value) values (17, 22, "active", "activeX");
insert into Tasks(id, kr_id, state, value) values (18, 22, "failed", "failedX");
insert into Tasks(id, kr_id, state, value) values (19, 22, "active", "activeX");
