-- Local development data. This file is loaded only by devel/run.py.

insert into PValues(id, name, description) values
  (1, 'Health', 'Energy, movement, recovery, and sustainable habits.'),
  (2, 'Career', 'Building useful skills and doing meaningful work.'),
  (3, 'Finances', 'A stable foundation and deliberate investing.'),
  (4, 'Relationships', 'Time and attention for the people who matter.'),
  (5, 'Personal growth', 'Learning, creativity, and reflection.'),
  (6, 'Zabava a Volny Cas', 'Leisure, recreation, and time to enjoy.');

insert into Objectives(id, value_id, state, name, description, date_created, date_finished) values
  (1, 1, 'active', 'Feel energetic throughout the week', 'Build a routine that supports good sleep, regular movement, and focused work.', '2026-07-01', ''),
  (2, 1, 'active', 'Build strength without burnout', 'Train consistently while leaving enough room for recovery.', '2026-06-15', ''),
  (3, 1, 'failed', 'Run a spring half marathon', 'This was paused after an injury; keep it as a useful historical example.', '2026-02-01', '2026-04-20'),
  (4, 2, 'active', 'Deliver a stronger portfolio', 'Turn recent work into a concise portfolio and ask for actionable feedback.', '2026-07-05', ''),
  (5, 2, 'achieved', 'Complete the architecture course', 'Finish the course and capture the key practices to apply at work.', '2026-03-01', '2026-06-10'),
  (6, 3, 'active', 'Build a six-month emergency fund', 'Automate saving and review monthly spending.', '2026-05-01', ''),
  (7, 4, 'active', 'Be more present with family', 'Create regular space for conversations and shared time.', '2026-07-10', ''),
  (8, 5, 'active', 'Read with intention', 'Keep a small, realistic reading habit and record useful ideas.', '2026-07-12', ''),
  (9, 1, 'achieved', 'Establish a consistent sleep routine', 'A previous successful health objective, kept as an example of a completed outcome.', '2026-01-05', '2026-02-14'),
  (10, 1, 'achieved', 'Cook dinner at home on weekdays', 'Plan simple meals and reduce last-minute takeaway decisions.', '2026-02-01', '2026-03-31'),
  (11, 1, 'achieved', 'Complete a month of daily mobility work', 'Ten minutes of mobility after the morning routine.', '2026-03-01', '2026-04-02'),
  (12, 1, 'failed', 'Avoid all sugar for a month', 'The goal was too restrictive and not sustainable.', '2026-01-10', '2026-01-24'),
  (13, 1, 'failed', 'Train six days every week', 'The training volume left too little recovery time.', '2026-03-15', '2026-04-18'),
  (14, 1, 'failed', 'Meditate for an hour every day', 'The starting commitment was unrealistic for the schedule.', '2026-04-01', '2026-04-18'),
  (15, 1, 'achieved', 'Build a regular walking habit', 'A first successful attempt at making movement part of the week.', '2023-04-01', '2023-06-30'),
  (16, 1, 'failed', 'Do yoga every morning for 90 days', 'The routine was too ambitious for travel and busy mornings.', '2023-08-01', '2023-09-12'),
  (17, 1, 'achieved', 'Reduce weekday caffeine', 'Replace the afternoon coffee with tea or water.', '2024-01-10', '2024-03-20'),
  (18, 1, 'failed', 'Run a marathon in autumn', 'The plan did not leave enough time to build mileage safely.', '2024-06-01', '2024-10-05'),
  (19, 1, 'achieved', 'Eat vegetables with lunch every weekday', 'Make vegetables the default part of weekday lunches.', '2025-02-01', '2025-04-30'),
  (20, 1, 'failed', 'Never use a screen after 20:00', 'The absolute rule did not work with occasional evening plans.', '2025-09-01', '2025-10-15'),
  (21, 1, 'active', 'Improve daily hydration', 'Make drinking water the default throughout the workday.', '2026-07-20', ''),
  (22, 1, 'active', 'Build a sustainable morning routine', 'Start the day with a calm, repeatable sequence that supports energy and focus.', '2026-07-18', ''),
  (23, 1, 'active', 'Reduce recurring neck tension', 'Use short movement breaks and improve the desk setup.', '2026-07-16', ''),
  (24, 1, 'active', 'Cook more varied healthy lunches', 'Collect a small rotation of quick lunches that are easy to prepare.', '2026-07-14', ''),
  (25, 1, 'active', 'Protect a consistent recovery day', 'Keep one lower-intensity day each week for rest and recovery.', '2026-07-11', '');

insert into KeyResults(id, objective_id, state, name, description, s, m, a, r, t, date_created, date_reviewed) values
  (1, 1, 'active', 'Average at least 7.5 hours of sleep', 'Track sleep on work nights and adjust the evening routine.', 'true', 'Weekly average is at least 7.5 hours', 'Keep a consistent 23:00 bedtime', 'true', '2026-07-10', '2026-07-01', '2026-07-16'),
  (2, 1, 'active', 'Walk 8,000 steps on five days each week', 'Use a lunch walk and short evening walk as defaults.', 'true', 'Five days per week reach 8,000 steps', 'Start with four days if a week is busy', 'true', '2026-07-19', '2026-07-01', '2026-07-18'),
  (3, 1, 'completed', 'Prepare a simple weekday breakfast plan', 'Three repeatable breakfasts are prepared in advance.', 'true', 'Three recipes are written and ingredients are available', 'Use familiar recipes only', 'true', '2026-07-15', '2026-07-01', '2026-07-14'),
  (4, 2, 'active', 'Complete two full-body strength sessions weekly', 'Focus on a small routine that is easy to repeat.', 'true', 'Two sessions are logged each week for six weeks', 'Use 30-minute sessions', 'true', '2026-09-01', '2026-06-15', '2026-07-17'),
  (5, 2, 'active', 'Log a short recovery note after every session', 'Note soreness, sleep, and whether the next session should change.', 'true', 'A note exists after every completed session', 'Use a one-minute template', 'true', '', '2026-06-15', '2026-07-17'),
  (6, 3, 'failed', 'Run 15 km without stopping', 'Training was interrupted by an injury.', 'true', 'Complete one 15 km run', 'Resume only after recovery', 'true', 'by the end of spring', '2026-02-01', '2026-04-20'),
  (7, 4, 'active', 'Publish three portfolio case studies', 'Each case study explains the problem, decisions, and outcome.', 'true', 'Three public case studies are published', 'Reuse existing project material', 'true', '2026-08-31', '2026-07-05', '2026-07-18'),
  (8, 4, 'active', 'Ask two peers for portfolio feedback', 'Send a focused request with specific questions.', 'true', 'Two feedback conversations are completed', 'Choose peers who know the work', 'true', '2026-08-10', '2026-07-05', '2026-07-12'),
  (9, 5, 'completed', 'Finish the architecture course', 'All modules, exercises, and notes are complete.', 'true', 'Course completion certificate and summary notes', 'Schedule two focused sessions weekly', 'true', '2026-06-01', '2026-03-01', '2026-06-10'),
  (10, 6, 'active', 'Save 12,000 EUR for emergencies', 'Automate the transfer on payday.', 'true', 'Emergency account balance reaches 12,000 EUR', 'Start with the current monthly surplus', 'true', '2026-12-31', '2026-05-01', '2026-07-01'),
  (11, 6, 'active', 'Review spending at the end of each month', 'Classify spending and decide one adjustment for the next month.', 'true', 'One review is completed each month', 'Use the existing bank export', 'true', '', '2026-05-01', '2026-06-30'),
  (12, 7, 'active', 'Plan one shared activity each week', 'Choose a simple activity together and protect the time.', 'true', 'One shared activity happens every week for two months', 'Keep activities local and low effort', 'true', '2026-09-15', '2026-07-10', '2026-07-17'),
  (13, 8, 'active', 'Read six books this quarter', 'Alternate fiction and non-fiction and note one useful takeaway.', 'true', 'Six finished books are recorded', 'Read 20 minutes before bed', 'true', '2026-09-30', '2026-07-12', '2026-07-18'),
  (14, 8, 'active', 'Write a short note for every finished book', 'Capture an idea worth applying or discussing.', 'true', 'One note exists for every finished book', 'Use a three-sentence template', 'true', '', '2026-07-12', '2026-07-12'),
  (15, 9, 'completed', 'Walk 7,000 steps on four days each week', 'The walking routine became stable by the end of the quarter.', 'true', 'Four days each week reach 7,000 steps', 'Use the commute and lunch break', 'true', '2023-06-30', '2023-04-01', '2023-06-30'),
  (16, 9, 'completed', 'Plan one longer weekend walk each month', 'A low-pressure way to explore nearby places.', 'true', 'Three longer walks are completed', 'Invite a friend when possible', 'true', '2023-06-30', '2023-04-01', '2023-06-28'),
  (17, 10, 'failed', 'Complete 90 morning yoga sessions', 'The initial target did not account for travel and recovery days.', 'true', 'Ninety sessions are logged', 'Use a ten-minute routine', 'true', '2023-10-30', '2023-08-01', '2023-09-12'),
  (18, 11, 'completed', 'Replace afternoon coffee on four weekdays', 'The new routine reduced late-day caffeine.', 'true', 'Four weekdays each week use tea or water', 'Keep tea at the desk', 'true', '2024-03-20', '2024-01-10', '2024-03-20'),
  (19, 12, 'failed', 'Complete a 30 km long run', 'The mileage increase was too aggressive.', 'true', 'One 30 km run is completed comfortably', 'Increase distance gradually', 'true', '2024-09-30', '2024-06-01', '2024-10-05'),
  (20, 13, 'completed', 'Prepare vegetables for five weekday lunches', 'A simple Sunday preparation routine made lunch easier.', 'true', 'Five lunches include prepared vegetables each week', 'Use frozen vegetables when needed', 'true', '2025-04-30', '2025-02-01', '2025-04-30'),
  (21, 13, 'completed', 'Try six new vegetable-based recipes', 'The recipe list now has several reliable favourites.', 'true', 'Six recipes are cooked and rated', 'Cook one recipe each weekend', 'true', '2025-04-30', '2025-02-01', '2025-04-22'),
  (22, 14, 'failed', 'Keep every evening screen-free after 20:00', 'The rule was not flexible enough for real life.', 'true', 'Thirty consecutive screen-free evenings', 'Allow exceptions for planned events', 'true', '2025-10-01', '2025-09-01', '2025-10-15'),
  (23, 21, 'active', 'Drink a glass of water after waking', 'Start hydration before coffee or breakfast.', 'true', 'Complete this on five weekdays each week', 'Keep a glass beside the bed', 'true', '2026-08-15', '2026-07-20', '2026-07-20'),
  (24, 21, 'active', 'Keep a water bottle at the desk', 'Make water immediately available during focused work.', 'true', 'Bottle is filled and present on every workday', 'Choose a one-litre bottle', 'true', '2026-08-15', '2026-07-20', '2026-07-20'),
  (25, 21, 'active', 'Finish two litres of water daily', 'Use the bottle as a simple visual measure.', 'true', 'Reach two litres on five days per week', 'Track refills instead of every sip', 'true', '2026-08-31', '2026-07-20', '2026-07-20'),
  (26, 21, 'active', 'Drink water before each meal', 'Use meals as natural hydration reminders.', 'true', 'Complete before breakfast, lunch, and dinner', 'Keep water on the table', 'true', '2026-08-15', '2026-07-20', '2026-07-20'),
  (27, 21, 'active', 'Replace one sweet drink each day', 'Choose water or unsweetened tea instead.', 'true', 'Replace at least five sweet drinks each week', 'Prepare cold tea in advance', 'true', '2026-08-31', '2026-07-20', '2026-07-20'),
  (28, 21, 'active', 'Have water ready before exercise', 'Prepare a bottle as part of changing for activity.', 'true', 'Bring water to every planned session', 'Leave a spare bottle in the gym bag', 'true', '2026-08-15', '2026-07-20', '2026-07-20'),
  (29, 21, 'active', 'Refill the bottle after lunch', 'Avoid relying on thirst during the afternoon.', 'true', 'Refill before returning to afternoon work', 'Set a lunch-end reminder', 'true', '2026-08-15', '2026-07-20', '2026-07-20'),
  (30, 21, 'active', 'Track hydration for two weeks', 'Learn which parts of the day need a better cue.', 'true', 'Log intake for fourteen consecutive days', 'Use a short phone note', 'true', '2026-08-03', '2026-07-20', '2026-07-20'),
  (31, 21, 'active', 'Add electrolytes after long workouts', 'Use them only after longer or hotter sessions.', 'true', 'Use an electrolyte drink after every 90-minute session', 'Keep packets with workout supplies', 'true', '2026-08-31', '2026-07-20', '2026-07-20'),
  (32, 21, 'active', 'Notice afternoon energy levels', 'Relate hydration habits to the usual afternoon slump.', 'true', 'Record a brief 15:00 energy rating on ten workdays', 'Use a one-to-five scale', 'true', '2026-08-07', '2026-07-20', '2026-07-20'),
  (33, 21, 'active', 'Choose water when eating out', 'Keep the habit practical in social settings.', 'true', 'Order water first at four meals out', 'Ask for a carafe at the table', 'true', '2026-08-31', '2026-07-20', '2026-07-20'),
  (34, 21, 'active', 'Prepare a reusable travel bottle', 'Avoid losing the routine on days away from home.', 'true', 'Carry water on every commute for two weeks', 'Keep the bottle beside keys', 'true', '2026-08-10', '2026-07-20', '2026-07-20'),
  (35, 21, 'active', 'Avoid caffeine after midday', 'Reduce the chance of using coffee instead of rest and water.', 'true', 'No caffeinated drinks after 12:00 on five weekdays', 'Switch to herbal tea', 'true', '2026-08-31', '2026-07-20', '2026-07-20'),
  (36, 21, 'active', 'Review hydration weekly', 'Adjust cues based on what was missed that week.', 'true', 'Complete a five-minute review every Sunday', 'Use the hydration notes', 'true', '2026-08-31', '2026-07-20', '2026-07-20'),
  (37, 21, 'active', 'Keep water by the bed overnight', 'Make it easy to drink if waking thirsty.', 'true', 'Water is prepared beside the bed each evening', 'Use a covered glass', 'true', '2026-08-15', '2026-07-20', '2026-07-20');

insert into Tasks(id, kr_id, state, value) values
  (1, 1, 'finished', 'Set a 22:30 evening reminder'),
  (2, 1, 'active', 'Keep phone outside the bedroom'),
  (3, 2, 'finished', 'Walk after lunch on Monday'),
  (4, 2, 'active', 'Plan the Friday evening walk'),
  (5, 4, 'active', 'Schedule Tuesday strength session'),
  (6, 4, 'active', 'Schedule Saturday strength session'),
  (7, 7, 'finished', 'Select the first portfolio project'),
  (8, 7, 'active', 'Draft the case study outline'),
  (9, 10, 'active', 'Confirm the automated monthly transfer'),
  (10, 12, 'active', 'Suggest a weekend walk'),
  (11, 13, 'active', 'Choose the next book'),
  (12, 1, 'active', 'Set the bedroom lights to dim at 21:30'),
  (13, 1, 'active', 'Prepare tomorrow’s clothes before bed'),
  (14, 1, 'active', 'Stop checking work messages after 21:00'),
  (15, 1, 'active', 'Write down the next day’s top priority'),
  (16, 1, 'active', 'Charge the phone outside the bedroom'),
  (17, 1, 'active', 'Make a cup of caffeine-free tea'),
  (18, 1, 'active', 'Read ten pages of a book before sleep'),
  (19, 1, 'active', 'Open the window for ten minutes before bed'),
  (20, 1, 'active', 'Record bedtime in the sleep log'),
  (21, 1, 'active', 'Set an alarm for a consistent wake-up time');

insert into ObjectiveIdeas(id, objective_id, value) values
  (1, 1, 'Try a short evening stretching routine'),
  (2, 4, 'Add a before-and-after section to each case study'),
  (3, 7, 'Create a shared list of low-effort activity ideas'),
  (4, 21, 'Keep a jug of chilled water in the fridge'),
  (5, 21, 'Try sparkling water with lemon as an afternoon alternative'),
  (6, 21, 'Create a simple bottle-refill checklist for workdays'),
  (7, 21, 'Put a water reminder beside the coffee machine'),
  (8, 21, 'Find a travel bottle that fits the backpack side pocket'),
  (9, 21, 'Prepare unsweetened iced tea for warm days'),
  (10, 21, 'Add a water break to the calendar between meetings'),
  (11, 21, 'Keep an extra bottle in the car'),
  (12, 21, 'Test whether drinking before lunch reduces afternoon tiredness'),
  (13, 21, 'Make a short list of hydrating snacks for hot days');
